//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fool_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {

        }

        public Order(int orderid, int offerid, int customerid, int status, decimal purchaseprice, DateTime startdate, DateTime enddate, DateTime purchasedate, int productid)
        {
            this.OrderId = orderid;
            this.OfferId = offerid;
            this.CustomerId = customerid;
            this.Status = status;
            this.PurchasePrice = purchaseprice;
            this.StartDate = startdate;
            this.EndDate = enddate;
            this.PurchaseDate = purchasedate;
            this.ProductId = productid;
        }

        public int OrderId { get; set; }
        public int OfferId { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public int CustomerId { get; set; }
        public int Status { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
