//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fool_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Offers = new HashSet<Offer>();
            this.Orders = new HashSet<Order>();
        }

        public Product(string name, int brand, int status, string term)
        {
            this.Name = name;
            this.Brand = brand;
            this.Status = status;
            this.Term = term;
            this.DateCreated = DateTime.Now;
            this.DateModified = DateTime.Now;
            this.Status = 1;
            this.Offers = new HashSet<Offer>();
            this.Orders = new HashSet<Order>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<int> Brand { get; set; }
        public string Term { get; set; }
        public int Status { get; set; }
    
        public virtual Brand Brand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
